Código para explorar tensores en pytorch

Para instalar pytorch y los otros paquetes matemáticos:

conda install pytorch cpuonly -c pytorch
conda install pandas numpy matplotlib seaborn

opción "-c" es para definir el canal desde donde se descarga

In [1]:
import torch
print(torch.__version__)
import numpy as np

2.5.1


In [3]:
#  https://pytorch.org/docs/stable/index.html



x = torch.ones(2,2, dtype = torch.int)   #torch.float16 
print(x)
print('tipo del tensor',x.dtype)
print(x.size())

y = torch.rand(2,2)
# suma, producto y división, elemento por elemento
print(x+y)
print(x*y)
z = x/y-torch.div(x,y)
print(z)

x = torch.empty(2,2,2,3)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tipo del tensor torch.int32
torch.Size([2, 2])
tensor([[1.2627, 1.0499],
        [1.2049, 1.2858]])
tensor([[0.2627, 0.0499],
        [0.2049, 0.2858]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[[-3.2295e-30,  1.2752e-42,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])


In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x tiene shape (2, 3), total 6 elementos
y = x.view(6)  # y tendrá shape (6,)
print(y)  # tensor([1, 2, 3, 4, 5, 6])


tensor([1, 2, 3, 4, 5, 6])


In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape (2, 3), total 6 elementos
w = x.view(3, -1)  # PyTorch calcula la segunda dimensión para que 3 * ? = 6 -> ? = 2
print(w)
# tensor([[1, 2],
#         [3, 4],
#         [5, 6]])


tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
x = torch.rand(2,3)
print(f'despliegue parcial del tensor {x[:,2]}')

print(f'me da el valor, como escalar, de dimension 1 {x[0,1].item()}')
#.item() convierte ese tensor escalar (tensor de dimensión 0) en un valor numérico de Python (float)
print(type(x[0,1].item()))  # <class 'float'>

print(f'distinto a {x[0,1]} ?')
print(f'tipo de x {type(x[0,1])}')

# de elemento numpy a tensor de PyTorch
a = np.ones(5)
b= torch.from_numpy(a)

print(b)



despliegue parcial del tensor tensor([0.4597, 0.2962])
me da el valor, como escalar, de dimension 1 0.36950504779815674
<class 'float'>
distinto a 0.36950504779815674 ?
tipo de x <class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [8]:
x = torch.rand(2,3)
y = x.view(6)
w = x.view(3, -1)
xx = x.numpy()

# view() cambia la forma del tensor sin copiar los datos, creando una vista del tensor original.
# y = x.view(6) convierte x en un tensor 1D de 6 elementos.
# w = x.view(3, -1) reorganiza x en una matriz con 3 filas y el número de columnas que PyTorch 
# calcule automáticamente para mantener el mismo número total de elementos.
#view() solo funciona si el tensor es contiguo en memoria. Si no, hay que usar .contiguous() antes.
# Un tensor es contiguo si sus elementos están almacenados de forma secuencial en memoria, 
# siguiendo el orden natural del tensor (por ejemplo, fila por fila en un tensor 2D).

#  Compartición de memoria entre tensores (herencia de datos)

print(f'x antes de la adicion {x}')
print(f'xx -x.numpy- antes de la adición en x {xx}')
print(f'y -x.view antes de la adición en x {y}')

x.add_(3)

print("")
print("los hijos heredan del padre")
print(f'x después de la adicion en x {x}')
print(f'xx -x.numpy- después de la adición en x {xx}')
print(f'y -x.view - después de la adición en x {y}')

print("")
print("los padres heredan de los hijos")

y.add_(5)

print(f'x después de la adicion en y {x}')
print(f'xx -x.numpy- después de la adición en y {xx}')
print(f'y -x.view - después de la adición en y {y}')

print("")
print("se rompen las herencias")
y= y+10
print(f'x después de y+1 {x}')
print(f'xx -x.numpy- después de y+1 {xx}')
print(f'y -x.view - después de y+1 {y}')







x antes de la adicion tensor([[0.2354, 0.9580, 0.6629],
        [0.3758, 0.8892, 0.9274]])
xx -x.numpy- antes de la adición en x [[0.23543596 0.95804584 0.6628975 ]
 [0.37582576 0.88919854 0.9274034 ]]
y -x.view antes de la adición en x tensor([0.2354, 0.9580, 0.6629, 0.3758, 0.8892, 0.9274])

los hijos heredan del padre
x después de la adicion en x tensor([[3.2354, 3.9580, 3.6629],
        [3.3758, 3.8892, 3.9274]])
xx -x.numpy- después de la adición en x [[3.235436  3.958046  3.6628976]
 [3.375826  3.8891985 3.9274035]]
y -x.view - después de la adición en x tensor([3.2354, 3.9580, 3.6629, 3.3758, 3.8892, 3.9274])

los padres heredan de los hijos
x después de la adicion en y tensor([[8.2354, 8.9580, 8.6629],
        [8.3758, 8.8892, 8.9274]])
xx -x.numpy- después de la adición en y [[8.2354355 8.958046  8.662897 ]
 [8.375826  8.889198  8.927403 ]]
y -x.view - después de la adición en y tensor([8.2354, 8.9580, 8.6629, 8.3758, 8.8892, 8.9274])

se rompen las herencias
x después de y+1 

In [9]:
# la misma lógica pero cambiando sólo elementos

xx = torch.tensor([1, 2, 3, 4, 5, 6])

# Reshape the tensor
yy = xx.view(2, 3)

# Change a value in xx
xx[0] = 10

# Both xx and yy reflect the change
print("xx:", xx)
print("yy:", yy)

# Change a value in yy
yy[0, 1] = 20

# Both xx and yy reflect the change
print("xx after modifying yy:", xx)
print("yy after modifying yy:", yy)

# finalmente, si se quiere romper la herencia de datos, se puede usar .clone() o .detach()
# .clone() crea una copia del tensor, mientras que .detach() crea un nuevo tensor
# que comparte los mismos datos pero no está conectado al grafo de autograd.


xx: tensor([10,  2,  3,  4,  5,  6])
yy: tensor([[10,  2,  3],
        [ 4,  5,  6]])
xx after modifying yy: tensor([10, 20,  3,  4,  5,  6])
yy after modifying yy: tensor([[10, 20,  3],
        [ 4,  5,  6]])


In [10]:
#para calcular el gradiente de un tensor, se debe establecer requires_grad=True
x = torch.ones(2, 2, requires_grad=True)
print(f'x con gradiente {x}')

x con gradiente tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [11]:
print(torch.cuda.is_available())
# we can handle where are the mathematical elements
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")

print(f"x is on: {x.device}")
print(f"y is on: {y.device}")
print(f"z is on: {z.device}")



False
x is on: cpu
y is on: cpu
z is on: cpu
